### ISSUE TITLE
[ENG-177] Referencing a secret, that reference another one, from inside a folder cause an interpretation error on Vercel

### ISSUE THREAD

**Issue by abdalem** [Infisical/infisical#1073] opened 2023-10-10 05:21 UTC
### Describe the bug

When a secret (A) reference another one (B), and we reference that secret (A) from a secret (C) that is inside a folder, that break the reference from A to B. I've seen a wrong value in the Vercel synced ENV, did not test elsewhere, even in local.

### To Reproduce

1. Go to Env Secrets (eg: `staging`)
2. Add a secret B that have a value (eg: `testing`)
3. Add a secret A that have a value referencing B (eg: `some-${B}`)
4. Create a folder
5. Create a secret C that a value referencing A (eg: `folder-${staging.A}`)
6. See that the value of C synced in Vercel is `folder-some-${B}`

### Expected behavior

It should be `folder-some-testing`

### Platform you are having the issue on:

Vercel

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-177](https://linear.app/infisical/issue/ENG-177/referencing-a-secret-that-reference-another-one-from-inside-a-folder)</sub>

**Comment by akhilmhdh** [comment] 2023-10-10 06:36
Hey @abdalem 

Sorry that's a wrong conception on referencing and its working as intended. I'll tell you why!

So when the interpolation string is `${<any value without dots like B, A>}` it means secret key named as `A or B` in the same board. The same board means relative to the board that ur calling.

So here it means B is variable from the folder u created which was not present. Thus it didn't got interpolated.

You can get it working by interpolating like this `staging.B` inside some. This is the same principle as relative file path and absolute file path.

Closing as this is expected behavoir

**Closed by akhilmhdh** 2023-10-10 06:36 UTC
