### ISSUE TITLE
Frontend does not redirect after login if 2fa is enabled

### ISSUE THREAD

**Issue by shark0der** [Infisical/infisical#569] opened 2023-05-09 10:57 UTC
### Describe the bug
When 2fa is enabled, after logging in and providing the code the frontend does not redirect to the dashboard.

### To Reproduce
1. Enable 2fa in user settings
2. Go to the login page
3. Fill in user/password
4. The app will prompt for the 2fa code. Paste the code from the email
5. Press Verify

None of the requests fail and there's no error in the browser console. The last request is the one to `/api/v1/organization/<user-id>/my-workspaces` and it returns this response: `{"workspaces":[]}`.
I didn't get to set up any workspaces.

### Expected behavior
After the code is verified a redirect should happen to the dashboard.

### Screenshots
![image](https://github.com/Infisical/infisical/assets/528959/22b1264f-5d86-4cb6-b8ec-cd57e380c4dd)

### Platform you are having the issue on:
```
Ubuntu: 22.04
Docker: 23.0.6-1~ubuntu.22.04~jammy
Docker compose plugin: 2.17.3-1~ubuntu.22.04~jammy

infisical/frontend      latest    eed68a0eb9d8
infisical/backend       latest    99e2e523e1f3
```

### Additional context
.

**Comment by shark0der** [comment] 2023-05-09 11:41
Setting `isMfaEnabled: false` in the database allowed me to login again.

**Comment by vmatsiiako** [comment] 2023-06-07 20:02
@shark0der is this happening in Infisical Cloud or for a self-hosted version? 

I wasn't able to reproduce it in the Cloud

**Comment by dangtony98** [comment] 2023-06-20 03:08
Hi @shark0der!

Is this still an issue? I'll close it out if it isn't.

**Comment by akhilmhdh** [comment] 2023-07-15 07:16
Closing as we couldn't reproduce it any more. Feel free to re-open this or create a new one if its still valid

**Closed by akhilmhdh** 2023-07-15 07:16 UTC
Labels: 🐞 bug
