### ISSUE TITLE
Secrets containing angle brackets are escaped from Web UI

### ISSUE THREAD

**Issue by harveysanders** [Infisical/infisical#863] opened 2023-08-14 21:37 UTC
### Describe the bug
Web secrets UI escapes angle brackets included in a secret value.

#### Context:
Hi!
I have a few mailbox strings set in my infisical secrets. These strings sometimes contain angle brackets to include a display name along with the email address. If the angle brackets are include in a secret's value, that portion is not displayed in the Web UI. Thankfully, the actual value is not changed. I assume this is due to HTML escaping, but is there a way we can display the values as originally input?

### To Reproduce
1. Create a secret with a value that contains angle brackets `<` `>`
2. View the secrets in the web UI
3. The portion of the value within the brackets is not visible (presumably escaped for HTML sanitization)

### Expected behavior
The web UI should display the secret value as inputed

### Screenshots
```
$ infisical secrets set EMAIL_SUPPORT="Support <support@example.com>" --env=staging

┌───────────────┬───────────────────────────────┬───────────────────────┐
│ SECRET NAME   │ SECRET VALUE                  │ STATUS                │
├───────────────┼───────────────────────────────┼───────────────────────┤
│ EMAIL_SUPPORT │ Support <support@example.com> │ SECRET VALUE MODIFIED │
└───────────────┴───────────────────────────────┴───────────────────────┘
```

![image](https://github.com/Infisical/infisical/assets/9354822/a5256f37-e30d-4c9e-a7bb-a3550b05bf06)

**Comment by akhilmhdh** [comment] 2023-08-15 05:54
Duplicate of #820

**Comment by subhajit20** [comment] 2023-08-15 16:23
Hey @harveysanders  @akhilmhdh  I would like to take this issue.
Would you guys assign it to me?

**Comment by harveysanders** [comment] 2023-08-15 19:56
@subhajit20 It looks like @shlokmehta21 is taking it via #820. However, they needed some help debugging. Maybe you could give them some pointers on how to debug/log the issue

**Comment by akhilmhdh** [comment] 2023-08-25 06:17
Hey @harveysanders This has been fixed with our recent release. Let me know if your still facing the same issue. Closing this issue

**Closed by akhilmhdh** 2023-08-25 06:17 UTC
Labels: 🐞 bug, 👀 frontend
