### ISSUE TITLE
Better logs for operator errors

### ISSUE THREAD

**Issue by JamesArthurHolland** [Infisical/infisical#746] opened 2023-07-13 12:37 UTC
When you have multiple projects, and therefore multiple tokens, when there is an issue with a token or k8s InfisicalSecret, it's not clear which is at fault.

```
unable to reconcile Infisical Secret because [err=
failed to get secrets because [err=CallGetSecretsV3: Unsuccessful response. Please make sure your secret path, workspace and environment name are all correct [response={}]]]. Will requeue after [requeueTime=1m0s]
```

Loggin the name of which project it failed to get secrets from would be very useful.

**Comment by subh-cs** [comment] 2023-07-15 04:31
Hi @akhilmhdh, I would like to work on this issue. Can you assign this to me?

**Comment by akhilmhdh** [comment] 2023-07-15 07:12
Yah sure @subh-cs . 

CC: @maidul98

**Comment by maidul98** [comment] 2023-07-16 15:34
Let us know if you need help @subh-cs

**Comment by subh-cs** [comment] 2023-07-16 15:38
Hi @maidul98, Actually I do. 
How can I reproduce this error? I found the respective code though.

**Comment by maidul98** [comment] 2023-07-16 18:45
Are you familiar with kube builder https://github.com/kubernetes-sigs/kubebuilder because the operator is made with it. If you are not familiar with it, no worries, one of us will take care of it

**Closed** 2023-07-28 19:11 UTC
Labels: good first issue, k8-operator
