### ISSUE TITLE
`Enter passphrase to unlock` for `file` vault is printed to stdout instead of stderr

### ISSUE THREAD

**Issue by NiklasRosenstein** [Infisical/infisical#941] opened 2023-09-03 10:08 UTC
### Describe the bug

See title

### To Reproduce

1. Use the `file` vault with `infisical vault set file`
2. Go to any project and run `infisical export > .env` and notice that
  1. The passphrase question isn't printed
  2. After entering your password anyway you see the passphrease question in `.env`

### Expected behavior

The question is printed to stderr instead.

### Additional context

Infisical CLI v0.12.2

**Comment by maidul98** [comment] 2023-09-04 13:31
Good catch @NiklasRosenstein

**Comment by pratik-codes** [comment] 2023-09-16 19:46
@maidul98 can I contribute to this issue? I can pick it up in case its fine.

**Comment by maidul98** [comment] 2023-09-16 20:00
@pratik-codes yes, you may work on this

**Comment by pratik-codes** [comment] 2023-09-19 14:20
Hey, @NiklasRosenstein @maidul98 a little more background on the issue would be helpful. This issue is happening from the infisical cli correct?

**Comment by NiklasRosenstein** [comment] 2023-09-20 15:34
Hey @pratik-codes, happy to hear you'd like to work on this. 😄 Though I'm not sure what additional info is missing, the steps to reproduce are described in the issue description above. 👀

**Comment by pratik-codes** [comment] 2023-09-20 18:07
Hey @NiklasRosenstein I was able to reproduce the issue and have got what the issue is. Just trying to figure out how to text changes of cli locally. Thanks for reverting though

**Comment by maidul98** [comment] 2023-09-20 23:06
@pratik-codes you may be a bit confused because the keyring related code is in a different package https://github.com/Infisical/go-keyring/blob/master/keyring_encrypted_file.go#L167

To solve this, you will likely have to keep the passphrase in a global variables so that each time it is needed, it can source from that location instead of having to ask the user again

**Comment by pratik-codes** [comment] 2023-09-23 15:37
Hi, @maidul98 just wanted to discuss the approach before going ahead with the solution. 

So basically my findings are `util.GetAllEnvironmentVariables` function calls the `GetCurrentLoggedInUserDetails` which calls the `GetUserCredsFromKeyRing` function. 
Which calls this -  keyring package and gets the keyring https://github.com/Infisical/go-keyring/blob/master/keyring_encrypted_file.go#L167

In this case, to solve it we will have to prompt the user to paraphrase get the input from the user and use it. 

My question is where should this be implemented? in the keyring package itself or prompt the user on the cli side itself and pass the password to the `Get` function of the keyring package and modify it to take the password as input as well.

This might be alot of question I know, but I wanted to discuss it before and do it right. Thanks 😄

**Comment by pratik-codes** [comment] 2023-09-23 17:49
Hi @maidul98 

The issue is may be related to the buffering behavior of the standard output stream (stdout) when using fmt.Println() in conjunction with term.ReadPassword(). The term.ReadPassword() function reads directly from the file descriptor, and it's possible that the output from fmt is buffered and not immediately flushed to the terminal.

Have made a fix for this in `go-keyring` - https://github.com/Infisical/go-keyring/pull/1

Also, do you want In case the password is incorrect the output file should not be generated completely? currently, it will be generated with the error written to it.


Let me know what do you think about the fix and if you think anything else/more can be done here.

**Comment by maidul98** [comment] 2023-09-25 22:32
@pratik-codes i have fixed your PR and merged it. You can have a look at my comment here https://github.com/Infisical/go-keyring/pull/1

@NiklasRosenstein the fix should be out in the next CLI release 0.13.2. Should be out in about 20 minutes https://github.com/Infisical/infisical/actions/runs/6305573109/job/17119226391

**Closed by maidul98** 2023-09-25 22:32 UTC
Labels: 🐞 bug, good first issue

**Comment by pratik-codes** [comment] 2023-09-26 05:42
@maidul98 I actually tried a similar approach to what you did, but It wasn't printing the prompt in the terminal for some reason. That is why I went with `log` approach.

**Comment by maidul98** [comment] 2023-09-26 06:09
@pratik-codes does it work for you now?

**Comment by pratik-codes** [comment] 2023-10-02 12:19
Yeap it works @maidul98

**Comment by NiklasRosenstein** [comment] 2023-10-11 16:41
@maidul98 @pratik-codes I realized the same is true for `infisical run`, e.g. if you do

    $ infisical run -- some command >/dev/null

I would expect it to print

```
Injecting 4 Infisical secrets into your application process
failed to wait for command termination: exit status 1
```

to stderr, but it ends up in stdout. This makes piping the output of commands wrapped with `infisical run` difficult.

**Comment by maidul98** [comment] 2023-10-12 09:00
@NiklasRosenstein can you please make a separate issue for this please?

**Comment by NiklasRosenstein** [comment] 2023-10-16 16:52
Certainly. https://github.com/Infisical/infisical/issues/1091
