### ISSUE TITLE
Secret values starting with less than symbol < won't save

### ISSUE THREAD

**Issue by decarbonise** [Infisical/infisical#890] opened 2023-08-23 19:58 UTC
### Describe the bug
When saving a secret value starting with `<`, Infisical says that the secret saved successfully, but upon retrieval the secret has not saved.

### To Reproduce
1. Create a secret with the < character at the start 
2. Save it
3. Refresh the page or retrieve the secret through the CLI
4. Note that the secret has not saved

### Platform you are having the issue on:
The CLI, Python SDK and web GUI are all affected

**Comment by akhilmhdh** [comment] 2023-08-24 04:51
@decarbonise it is saved successfully but we recently found out the loading values with `<` fails to load because of the new syntax highlight component we implemented. We will make sure this will get fixed by this week as more user's are reporting it

**Comment by decarbonise** [comment] 2023-08-24 06:59
@akhilmhdh Thanks for the update. Unfortunately the issue also applies to the CLI; if I use the secrets set command it doesn't save the value (it says it does but it doesn't show anything different on retrieval). So the issue goes beyond syntax highlighting and goes beyond the frontend

**Comment by akhilmhdh** [comment] 2023-08-24 07:04
If you have just created with `<` saved but didn't try to edit it again. I think then cli should be able to provide it. 

Cli should inject fine. Let me check it and try to reproduce it in cli. Frontend fix will be  raised soon

**Comment by decarbonise** [comment] 2023-08-24 07:18
Thanks @akhilmhdh; it wasn't working yesterday but seems to be today. I've tested for direct secrets, but is there a way to update a personal override secret using the CLI? Just had a look at the --help and can't see it, but if there is I'll test that because it seemed to behave oddly on the web

**Comment by akhilmhdh** [comment] 2023-08-25 06:18
Hey @decarbonise this has been fixed in our recent release and the ui wont break for another of those symbol 😅.

Let me know if your still facing it.

**Closed by akhilmhdh** 2023-08-25 06:18 UTC
Labels: 🐞 bug, 👀 frontend
