### ISSUE TITLE
Linting code automatically

### ISSUE THREAD

**Issue by SH5H** [Infisical/infisical#85] opened 2022-12-06 20:08 UTC
### Feature description
Using Husky and lint-staged for automatically linting before commit

### Why would it be useful?
can prevent submitting code with error

**Comment by maidul98** [comment] 2022-12-06 20:25
Duplicate of https://github.com/Infisical/infisical/issues/50

**Comment by maidul98** [comment] 2022-12-07 16:52
Awsome, if you can make a PR for it, i'd be happy to review it! Let me know if you have time to pick this up

**Closed** 2022-12-10 14:42 UTC
Labels: 💻 code improvements
